# Auto-generated by compose2nix.

{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."penpot-penpot-backend" = {
    image = "penpotapp/backend:2.16";
    environment = {
      "PENPOT_DATABASE_URI" = "postgresql://penpot-postgres/penpot";
      "PENPOT_DATABASE_USERNAME" = "penpot";
      "PENPOT_FLAGS" = "disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-mcp";
      "PENPOT_HTTP_SERVER_MAX_BODY_SIZE" = "367001600";
      "PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE" = "367001600";
      "PENPOT_OBJECTS_STORAGE_BACKEND" = "fs";
      "PENPOT_OBJECTS_STORAGE_FS_DIRECTORY" = "/opt/data/assets";
      "PENPOT_PUBLIC_URI" = "http://glacio:9001";
      "PENPOT_REDIS_URI" = "redis://penpot-valkey/0";
      "PENPOT_SMTP_DEFAULT_FROM" = "no-reply@example.com";
      "PENPOT_SMTP_DEFAULT_REPLY_TO" = "no-reply@example.com";
      "PENPOT_SMTP_HOST" = "penpot-mailcatch";
      "PENPOT_SMTP_PORT" = "1025";
      "PENPOT_SMTP_SSL" = "false";
      "PENPOT_SMTP_TLS" = "false";
      "PENPOT_TELEMETRY_ENABLED" = "true";
      "PENPOT_TELEMETRY_REFERER" = "compose";
    };
    environmentFiles = [
      "/var/lib/penpot/penpot-backend-secrets"
    ];
    volumes = [
      "penpot_penpot_assets:/opt/data/assets:rw"
    ];
    dependsOn = [
      "penpot-penpot-postgres"
      "penpot-penpot-valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-backend"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/penpot
      grep '^PENPOT_DATABASE_PASSWORD=' ${config.age.secrets."penpot-env".path} > /var/lib/penpot/penpot-backend-secrets
      grep '^PENPOT_SECRET_KEY=' ${config.age.secrets."penpot-env".path} >> /var/lib/penpot/penpot-backend-secrets
    '';
    unitConfig.Description = "Container penpot-penpot-backend generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_assets.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_assets.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-exporter" = {
    image = "penpotapp/exporter:2.16";
    environment = {
      "PENPOT_INTERNAL_URI" = "http://penpot-frontend:8080";
      "PENPOT_PUBLIC_URI" = "http://glacio:9001";
      "PENPOT_REDIS_URI" = "redis://penpot-valkey/0";
    };
    environmentFiles = [
      "/var/lib/penpot/penpot-exporter-secrets"
    ];
    dependsOn = [
      "penpot-penpot-valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-exporter"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-exporter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/penpot
      grep '^PENPOT_SECRET_KEY=' ${config.age.secrets."penpot-env".path} > /var/lib/penpot/penpot-exporter-secrets
    '';
    unitConfig.Description = "Container penpot-penpot-exporter generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-frontend" = {
    image = "penpotapp/frontend:2.16";
    environment = {
      "PENPOT_FLAGS" = "disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-mcp";
      "PENPOT_HTTP_SERVER_MAX_BODY_SIZE" = "367001600";
      "PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE" = "367001600";
      "PENPOT_PUBLIC_URI" = "http://glacio:9001";
    };
    volumes = [
      "penpot_penpot_assets:/opt/data/assets:rw"
    ];
    ports = [
      "9001:8080/tcp"
    ];
    dependsOn = [
      "penpot-penpot-backend"
      "penpot-penpot-exporter"
      "penpot-penpot-mcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-frontend"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container penpot-penpot-frontend generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_assets.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_assets.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-mailcatch" = {
    image = "sj26/mailcatcher:latest";
    ports = [
      "1080:1080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-mailcatch"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-mailcatch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container penpot-penpot-mailcatch generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-mcp" = {
    image = "penpotapp/mcp:2.16";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-mcp"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-mcp" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container penpot-penpot-mcp generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-postgres" = {
    image = "postgres:15";
    environment = {
      "POSTGRES_DB" = "penpot";
      "POSTGRES_INITDB_ARGS" = "--data-checksums";
      "POSTGRES_USER" = "penpot";
    };
    environmentFiles = [
      "/var/lib/penpot/penpot-postgres-secrets"
    ];
    volumes = [
      "penpot_penpot_postgres_v15:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U penpot"
      "--health-interval=2s"
      "--health-retries=5"
      "--health-start-period=2s"
      "--health-timeout=10s"
      "--network-alias=penpot-postgres"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/penpot
      grep '^POSTGRES_PASSWORD=' ${config.age.secrets."penpot-env".path} > /var/lib/penpot/penpot-postgres-secrets
    '';
    unitConfig.Description = "Container penpot-penpot-postgres generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_postgres_v15.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
      "docker-volume-penpot_penpot_postgres_v15.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-valkey" = {
    image = "valkey/valkey:8.1";
    environment = {
      "VALKEY_EXTRA_FLAGS" = "--maxmemory 128mb --maxmemory-policy volatile-lfu";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=valkey-cli ping | grep PONG"
      "--health-interval=1s"
      "--health-retries=5"
      "--health-start-period=3s"
      "--health-timeout=3s"
      "--network-alias=penpot-valkey"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."docker-penpot-penpot-valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container penpot-penpot-valkey generated by compose2nix.";
    after = [
      "docker-network-penpot_penpot.service"
    ];
    requires = [
      "docker-network-penpot_penpot.service"
    ];
    partOf = [
      "docker-compose-penpot-root.target"
    ];
    wantedBy = [
      "docker-compose-penpot-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-penpot_penpot" = {
    unitConfig.Description = "Network penpot_penpot generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f penpot_penpot";
    };
    script = ''
      docker network inspect penpot_penpot || docker network create penpot_penpot
    '';
    partOf = [ "docker-compose-penpot-root.target" ];
    wantedBy = [ "docker-compose-penpot-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-penpot_penpot_assets" = {
    unitConfig.Description = "Volume penpot_penpot_assets generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect penpot_penpot_assets || docker volume create penpot_penpot_assets
    '';
    partOf = [ "docker-compose-penpot-root.target" ];
    wantedBy = [ "docker-compose-penpot-root.target" ];
  };
  systemd.services."docker-volume-penpot_penpot_postgres_v15" = {
    unitConfig.Description = "Volume penpot_penpot_postgres_v15 generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect penpot_penpot_postgres_v15 || docker volume create penpot_penpot_postgres_v15
    '';
    partOf = [ "docker-compose-penpot-root.target" ];
    wantedBy = [ "docker-compose-penpot-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-penpot-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  age.secrets."penpot-env" = {
    file = ../secrets/penpot-env.age;
    mode = "0400";
  };
}
