# Auto-generated by compose2nix.

{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."sure-db" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_USER" = "sure_user";
    };
    environmentFiles = [
      "/var/lib/sure/sure-db-secrets"
    ];
    volumes = [
      "sure_postgres-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."docker-sure-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/sure
      VAL=$(cat ${config.age.secrets."postgres-password".path})
      # Ensure it's in the format POSTGRES_PASSWORD=...
      if [[ "$VAL" == *"="* ]]; then
        echo "$VAL" > /var/lib/sure/sure-db-secrets
      else
        echo "POSTGRES_PASSWORD=$VAL" > /var/lib/sure/sure-db-secrets
      fi
    '';
    after = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_postgres-data.service"
    ];
    requires = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_postgres-data.service"
    ];
    partOf = [
      "docker-compose-sure-root.target"
    ];
    wantedBy = [
      "docker-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-redis" = {
    image = "redis:latest";
    volumes = [
      "sure_redis-data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=redis-cli ping"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=redis"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."docker-sure-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_redis-data.service"
    ];
    requires = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_redis-data.service"
    ];
    partOf = [
      "docker-compose-sure-root.target"
    ];
    wantedBy = [
      "docker-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-web" = {
    image = "ghcr.io/we-promise/sure:latest";
    environment = {
      "DB_HOST" = "db";
      "DB_PORT" = "5432";
      "OPENAI_MODEL" = "llama3.1:8b";
      "OPENAI_URI_BASE" = "http://host.docker.internal:11434/v1";
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_USER" = "sure_user";
      "RAILS_ASSUME_SSL" = "false";
      "RAILS_FORCE_SSL" = "false";
      "REDIS_URL" = "redis://redis:6379/1";
      "SELF_HOSTED" = "true";
    };
    environmentFiles = [
      config.age.secrets."sure-env".path
      "/var/lib/sure/sure-db-secrets"
      "/var/lib/sure/sure-web-secrets"
    ];
    volumes = [
      "sure_app-storage:/rails/storage:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "sure-db"
      "sure-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--network-alias=web"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."docker-sure-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/sure
      VAL=$(cat ${config.age.secrets."secret-key-base".path})
      echo "SECRET_KEY_BASE=$VAL" > /var/lib/sure/sure-web-secrets
    '';
    after = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_app-storage.service"
    ];
    requires = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_app-storage.service"
    ];
    partOf = [
      "docker-compose-sure-root.target"
    ];
    wantedBy = [
      "docker-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-worker" = {
    image = "ghcr.io/we-promise/sure:latest";
    environment = {
      "DB_HOST" = "db";
      "DB_PORT" = "5432";
      "OPENAI_MODEL" = "llama3.1:8b";
      "OPENAI_URI_BASE" = "http://host.docker.internal:11434/v1";
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_USER" = "sure_user";
      "RAILS_ASSUME_SSL" = "false";
      "RAILS_FORCE_SSL" = "false";
      "REDIS_URL" = "redis://redis:6379/1";
      "SELF_HOSTED" = "true";
    };
    environmentFiles = [
      config.age.secrets."sure-env".path
      "/var/lib/sure/sure-db-secrets"
      "/var/lib/sure/sure-web-secrets"
    ];
    volumes = [
      "sure_app-storage:/rails/storage:rw"
    ];
    cmd = [ "bundle" "exec" "sidekiq" ];
    dependsOn = [
      "sure-db"
      "sure-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--network-alias=worker"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."docker-sure-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    preStart = ''
      mkdir -p /var/lib/sure
      VAL=$(cat ${config.age.secrets."secret-key-base".path})
      echo "SECRET_KEY_BASE=$VAL" > /var/lib/sure/sure-web-secrets
    '';
    after = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_app-storage.service"
    ];
    requires = [
      "docker-network-sure_sure_net.service"
      "docker-volume-sure_app-storage.service"
    ];
    partOf = [
      "docker-compose-sure-root.target"
    ];
    wantedBy = [
      "docker-compose-sure-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-sure_sure_net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f sure_sure_net";
    };
    script = ''
      docker network inspect sure_sure_net || docker network create sure_sure_net --driver=bridge
    '';
    partOf = [ "docker-compose-sure-root.target" ];
    wantedBy = [ "docker-compose-sure-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-sure_app-storage" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect sure_app-storage || docker volume create sure_app-storage
    '';
    partOf = [ "docker-compose-sure-root.target" ];
    wantedBy = [ "docker-compose-sure-root.target" ];
  };
  systemd.services."docker-volume-sure_postgres-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect sure_postgres-data || docker volume create sure_postgres-data
    '';
    partOf = [ "docker-compose-sure-root.target" ];
    wantedBy = [ "docker-compose-sure-root.target" ];
  };
  systemd.services."docker-volume-sure_redis-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect sure_redis-data || docker volume create sure_redis-data
    '';
    partOf = [ "docker-compose-sure-root.target" ];
    wantedBy = [ "docker-compose-sure-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-sure-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
