# Auto-generated by compose2nix.

{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."swiparr" = {
    image = "ghcr.io/npontious/swiparr:dev";
    environment = {
      "JELLYFIN_URL" = "http://glacio:8096";
      "RADARR_URL" = "http://glacio:7878";
      "SONARR_URL" = "http://glacio:8989";
      "PROVIDER" = "jellyfin";
      "TMDB_DEFAULT_REGION" = "US";
    };
    environmentFiles = [
      config.age.secrets."swiparr-env".path
    ];
    volumes = [
      "/mnt/storage/swiparr-data:/app/data:rw"
    ];
    ports = [
      "4321:4321/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=glacio:host-gateway"
      "--network-alias=swiparr"
      "--network=swiparr_default"
    ];
  };
  systemd.services."docker-swiparr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-swiparr_default.service"
    ];
    requires = [
      "docker-network-swiparr_default.service"
    ];
    partOf = [
      "docker-compose-swiparr-root.target"
    ];
    wantedBy = [
      "docker-compose-swiparr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-swiparr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f swiparr_default";
    };
    script = ''
      docker network inspect swiparr_default || docker network create swiparr_default
    '';
    partOf = [ "docker-compose-swiparr-root.target" ];
    wantedBy = [ "docker-compose-swiparr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-swiparr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  age.secrets."swiparr-env" = {
    file = ../secrets/swiparr-env.age;
    mode = "0400";
  };
}
